### ISSUE TITLE
Ad metadata

### ISSUE THREAD

**Issue by bluegoo192** [bluegoo192/Admiral#4]
We should keep data on each ad, including:
- User rating
- Performance cost(all ads have the same performance cost for now, since they're images)
- File size
- Contains malware? (this would come from users, so for now its just 'no' for all ads)
- Contains mature content (same as above)
- Category: media, luxury goods, basic goods, food, travel, service, or marketplace
- Tracks users? (no for all ads right now)

**Comment by Mzqu** [comment]
why this again
